spring:
  application:
    name: ta-conversation-storage
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone:
        http://ta-services-discovery:8761/eureka/

keycloak:
  realm: talk-active
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: ta-conversation-storage
  use-resource-role-mappings: true
  autodetect-bearer-only: true
  bearer-only: true
  principal-attribute: preferred_username