spring:
  application:
    name: ta-conversation-storage
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:5000/eureka/
